# Generated by Django 4.0.6 on 2022-07-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoas', '0001_initial'),
        ('app_receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_pessoas.pessoa'),
            preserve_default=False,
        ),
    ]
